# Generated by Django 5.2 on 2025-04-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_stock_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
