# Generated by Django 5.2 on 2025-04-27 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_estimated_delivery_date_and_more'),
        ('products', '0005_coupon_minimum_order_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_user_id_a87c6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_session_ad3c0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_guest_e_5522f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_c6dd84_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_52f79a_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='orders_orde_user_id_37fed6_idx'),
        ),
    ]
