# Generated by Django 5.2 on 2025-04-27 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon_review_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
